export class Keyboard {
    k_max_value = 0xffffffff;
    k_crouch = 38; //CTRL
    k_walk = 40; //SHIFT
    k_jump = 44; //SPACE
    k_backwards = 28; //S
    k_forward = 32; //W
    k_right = 13; //D
    k_left = 10; //A
    k_action = 15; //F
    k_shoot = 1; //LEFT BUTTON
    k_scope = 2; //RIGHT BUTTON
    k_reload = 27; //R
    k_change_weapon = 29; //T
    weapons1 = 1; //NUMBERS
    weapons2 = 2; //NUMBERS
    weapons3 = 3; //NUMBERS
    weapons4 = 4; //NUMBERS
    weapons5 = 5; //NUMBERS
    weapons6 = 6; //NUMBERS
    k_any_weapon = 26; //Q
    k_previous_weapon = 16; //MOUSE SCROLL UP
    k_next_weapon = 32; //MOUSE SCROLL DOWN
    k_player_weapon = 16; //????
    k_scoreboard = 55; //TAB
    k_map = 22; //M
    k_map_up = 92; //=
    k_map_down = 91; //-
    k_chat = 37; //ENTER
    k_chat_team = 64; //F2
    k_chat_all = 65; //F3
    k_chat_help = 21; //L
    k_chat_question = 31; //?
    k_radio_team = 35; //Z
    k_radio_personal = 33; //X
    k_radio_global = 12; //C
    k_bomb_defuse = 14; //E
    k_sensitivity_up = 49; //PAGE UP
    k_sensitivity_down = 50; //PAGE DOWN
    k_print = 70; //F8
    k_chat_command = 66; //F4
    k_aim_x = 11; //B
    k_record = 58; //SCROLL LOCK
    k_macro_execute = 69; //E?
    k_value1 = 57;
    k_value2 = 248;
    k_value3 = 16;
    k_value4 = 0;
    k_value5 = 232;
    macro1 = "";
    macro2 = "";
    macro3 = "";
    macro4 = "";
    macro5 = "";
}
