class AuthOpcodeACK {
    static BASE_GET_MYBOX_ACK = 421
	static BASE_GET_USER_GIFTLIST_ACK = 529
	static BASE_GET_MYCASH_ACK = 545
	static BASE_GET_SCHANNEL_LIST_ACK = 2049
	static BASE_GET_LOGIN_ERROR_ACK = 2062
	static BASE_GET_LOGIN_ACK = 2564
	static BASE_GET_MYINFO_ACK = 2566
	static BASE_GET_CONFIG_ACK = 2568
	static BASE_GET_ENTER_SERVER_ACK = 2578
	static BASE_GET_USER_ENTER_ACK = 2580
	static BASE_GET_PBLACKOUT_ACK = 2662
	static BASE_UPDATE_SCHANNEL_LIST_ACK = 2643
	static BASE_EXIT_GAME_ACK = 2655
	static BASE_GET_RANKINFO_ACK = 2669
	static BASE_GET_SOURCE_ACK = 2679
	static BASE_PUSH_PRESENT_ITEM_ACK = 2692
	static BASE_GET_URL_LIST_ACK = 2695
	static BASE_GET_INVENTORY_ACK = 2699
	static BASE_GET_INSERT_ITEM_ACK = 3588
	static BASE_GET_MACHINE_ACK = 31777
}

export {AuthOpcodeACK}