export enum ChannelServerEnum {
	CHANNEL_TYPE_NONE,
	CHANNEL_TYPE_NORMAL,
	CHANNEL_TYPE_BEGIN1,
	CHANNEL_TYPE_BEGIN2,
	CHANNEL_TYPE_CLAN,
	CHANNEL_TYPE_EXPERT,
	CHANNEL_TYPE_EXPERT2,
	CHANNEL_TYPE_CHAMPIONSHIP,
	CHANNEL_TYPE_NORMAL2,
	CHANNEL_TYPE,
}