export enum ClanLevelEnum{
    CLAN_LEVEL_SQUARD,
	CLAN_LEVEL_PLATOON,
	CLAN_LEVEL_COMPANY,
	CLAN_LEVEL_BATTALION,
	CLAN_LEVEL_REGIMENT,
	CLAN_LEVEL_BRIGADE,
	CLAN_LEVEL_DIVISION,
	CLAN_LEVEL_CORPS,
	CLAN_LEVEL_TOP,
	CLAN_LEVEL_MAX,
}