export enum GameServerEnum {
	S_CHANNEL_TYPE_UNDEFINED,
	S_CHANNEL_TYPE_ALL,
	S_CHANNEL_TYPE_NORMAL,
	S_CHANNEL_TYPE_NORMAL2,
	S_CHANNEL_TYPE_CLAN,
	S_CHANNEL_TYPE_BEGIN,
	S_CHANNEL_TYPE_EXPERT,
	S_CHANNEL_TYPE_CONBINATION,
	S_CHANNEL_TYPE_CHAMPIONSHIP,
	S_CHANNEL_TYPE,
}