export enum MessageClanEnum {
    INVITATION,
	REQUEST_APPROVED,
	REQUEST_REFUSED,
    INVITE_ACCEPT,
    INVITE_REJECTED,
    ABANDONED_CLAN,
    DELETED_CLAN,
    LEADER_CLAN,
    STAFF_CLAN,
    MEMBER_CLAN,
    MAX,
}