export enum MissionTypeEnum {
    NONE,                                   //0
    GET_KILL,                               //1
    GET_KILL_RIFLE,                         //2
    GET_KILL_SUBMACHINE,                    //3
    GET_KILL_SNIPER,                        //4 
    GET_KILL_SHOTGUN,                       //5
    GET_KILL_PISTOL,                        //6
    GET_KILL_MELEE,                         //7
    GET_KILL_K400,                          //8
    GET_DOUBLEKILL,                         //9
    GET_DOUBLEKILL_RIFLE,                   //10
    GET_DOUBLEKILL_SUBMACHINE,              //11
    GET_TRIPLEKILL,                         //12 
    GET_TRIPLEKILL_SUBMACHINE,              //13 
    GET_CHAINKILLER,                        //14
    GET_HEADSHOT,                           //15 
    GET_HEADSHOT_RIFLE,                     //16 
    GET_HEADSHOT_SUBMACHINE,                //17 
    KILL_ENEMY_THAT_USE_RIFLE,              //18
    KILL_ENEMY_THAT_USE_SUBMACHINE,         //19
    KILL_ENEMY_THAT_USE_SNIPER,             //20 
    KILL_ENEMY_THAT_USE_SHOTGUN,            //21
    PIERCINGSHOT,                           //22
    MASSKILL,                               //23
    ENTER,                                  //24
    DEATH,                                  //25
    ASSIST,                                 //26
    CHAINSLUGGER,                           //27
    DEATHBLOW,                              //28
    DEATHBLOW_RIFLE,                        //29
    DEATHBLOW_SUBMACHINE,                   //30
    DEATHBLOW_SNIPER,                       //31
    TOUCHDOWN,                              //32
    WINNER,                                 //33
    ACEATTACKER,                            //34
    INVASION,                               //35
    DEFEAT_THE_HUMANS,                      //36
    GET_KILL_1ROUND,                        //37
    KILL_ENEMY_THAT_USE_SUBMACHINE_1ROUND,  //38
    ASSIST_TREX,                            //39
    GET_CHAINKILLER_1ROUND,                 //40
    GET_TRIPLEKILL_1ROUND,                  //41
    KILL_ROOM_MASTER_1ROUND,                //42
    HAT_TRICK,                              //43
    GET_DOUBLEKILL_1ROUND,                  //44
    GET_HEADSHOT_1ROUND,                    //45
    GET_DOUBLEKILL_SNIPER,                  //46
    GET_CHAINHEADSHOT,                      //47
    GET_HEADSHOT_SNIPER,                    //48
    GET_KILL_GRENADE,                       //49
}